on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  ci_job:
    if: (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true))
    runs-on: ubuntu-latest
    steps:
      - name: Send CI webhook POST request
        run: |
          exec 3>&1
          status_code=$(curl -X POST "https://authenticdevelopment.net/api/ci" -d "secret=${{ secrets.CI_SECRET }}" -w "%{http_code}" -o >(cat >&3) 2>&1)
          if [ "$status_code" -ne "200" ]; then
            echo "Error occurred with status code: $status_code"
            exit 1
          fi
