name: Build and Deploy

on:
  push:
    branches:
      - main # or any branch you want to deploy from

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SESSION_SECRET_KEY: ${{ secrets.SESSION_SECRET_KEY }}
  ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
  AWS_S3_IMAGE_HOST: ${{ secrets.AWS_S3_IMAGE_HOST }}
  AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
  AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # specify your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Run Migrations
        run: npx prisma generate && npx prisma migrate deploy

      - name: Build
        run: npm run build # your build script

      - name: Install Production Packages
        run: rm -rf node_modules && npm i -f --omit=dev --ignore-scripts

      - name: Run Production Migrations
        run: npx prisma generate && npx prisma migrate deploy

      - name: Create .env File
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
          echo "SESSION_SECRET_KEY=${{ secrets.SESSION_SECRET_KEY }}" >> .env
          echo "ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}" >> .env
          echo "AWS_S3_IMAGE_HOST=${{ secrets.AWS_S3_IMAGE_HOST }}" >> .env
          echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> .env
          echo "AWS_KEY_ID=${{ secrets.AWS_KEY_ID }}" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> .env

      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ".next/,db/,node_modules/,package.json,.env,.sentryclirc" # or the directory where your JS files are
          target: ${{ secrets.TARGET }}

      - name: Restart Application with PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: /home/elvis/.nvm/versions/node/v18.18.2/bin/pm2 restart blitz
